Add note on setting `QUALITY` to tier 1 page
stellar/stellar-docs pull request #1152
Opened 2024-12-20 23:44 UTC by bboston7

This change adds a note to the docs for tier 1 orgs to help them properly set their org's quality level.

2025-01-08 17:22 UTC, ElliotFriend requested changes
This is a really great addition! Thanks for the contribution!

2025-01-08 17:22 UTC, ElliotFriend commented on docs/validators/tier-1-orgs.mdx
> +**NOTE:** Be sure to properly add your own validators to your validators' quorum sets. As a Tier 1 organization with three validators and history archives, we recommend declaring your organization [`
```suggestion
**NOTE:** Be sure to properly add your own validators to your validators' quorum sets. As a Tier 1 organization with three validators and history archives, SDF recommend declaring your organization [`HIGH` quality](./admin-guide/configuring.mdx#validator-quality) in your quorum set configuration. Declaring your organization at a lower quality level [may limit its participation in consensus](./admin-guide/configuring.mdx#impact-of-validator-quality-on-nomination).
```

2025-01-08 17:22 UTC, ElliotFriend commented on docs/validators/tier-1-orgs.mdx
> +**NOTE:** Be sure to properly add your own validators to your validators' quorum sets. As a Tier 1 organization with three validators and history archives, we recommend declaring your organization [`
Mostly markdown linking nitpicks here. They're silly and dumb, but it makes our build more reliable, especially with the newly introduced AI translations

However, I think it might be better suited to use `SDF`, rather than `we` in this instance. Not a deal-breaker, but worth thinking about, maybe.

If you wanted to wrap this note in an admonition (entirely optional, and also not a deal-breaker imo), you could do it like this:

```markdown
:::note

Be sure to properly ...

:::
```

2025-01-09 22:58 UTC, bboston7 commented
Thanks for the review Elliot! I wrapped the note in an admonition, which I think helps it stand out. Please take a look when you get a chance!

2025-01-21 19:18 UTC, ElliotFriend approved these changes
wonderful! Thanks!!

2025-01-21 19:18 UTC, merged