Fixing some code examples syntax languages
stellar/stellar-docs pull request #40
Opened 2022-09-27 22:02 UTC by ElliotFriend

Found one that needed fixing, and then did a quick search for any others that might be wrong. Here's the three I found. No big impact, but will help to make the docs more consistent.

Using `javascript` rather than `js` rendered "Example" into the code snippet headers. Weird 🤷🏻‍♂️ 

Signed-off-by: Elliot Voris <elliot@voris.me>

2022-09-28 17:17 UTC, briwylde08 commented
@tyvdh can you take a look at this when you get a chance?

2022-09-29 14:30 UTC, tyvdh requested changes

2022-09-29 14:30 UTC, tyvdh commented on docs/fundamentals-and-concepts/stellar-data-structures/assets.mdx
> -```json5
Comments don't render with `json` thus `json5` which does support comments

2022-09-29 14:30 UTC, tyvdh commented on docs/tutorials/follow-received-payments.mdx
> -```javascript
Does this actually matter?

2022-09-29 15:34 UTC, tyvdh commented on docs/fundamentals-and-concepts/stellar-data-structures/assets.mdx
> -```json5
Yeah we really only need those blocks if there's a list of different code languages otherwise it's a list of examples with one example

2022-09-29 15:35 UTC, merged

2022-09-29 15:36 UTC, tyvdh commented
Sure why not and if prism supports json5 somehow let's add that too so CodeExample can render that as well. Otherwise no worries. I did just merge this though so you may need to create a new PR now 😬

2022-09-29 15:38 UTC, ElliotFriend commented
On it!