Create 2024-04-18.mdx
stellar/stellar-docs pull request #530
Opened 2024-04-29 21:32 UTC by Danasacco

2024-04-30 14:10 UTC, ElliotFriend requested changes
looks good, except for a small markdown syntax issue.

2024-04-30 14:10 UTC, ElliotFriend commented on meeting-notes/2024-04-18.mdx
> +title: '2024-04-18'
```suggestion
---
title: '2024-04-18'
```

2024-04-30 14:10 UTC, ElliotFriend commented on meeting-notes/2024-04-18.mdx
> +title: '2024-04-18'
You'll need those three dashes at the top of the "frontmatter," too. Otherwise, it doesn't get parsed right.

2024-04-30 14:11 UTC, ElliotFriend commented
Also, it looks like that google drive file isn't shared right: https://developers-pr530.previews.kube001.services.stellar-ops.com/meetings/2024/04/18

![Screenshot 2024-04-30 at 9 11 27 AM](https://github.com/stellar/stellar-docs/assets/2024293/b96539f0-8f25-4d7d-ac7c-d2464fefb856)

2024-05-10 16:27 UTC, namankumar reviewed
lets gooo

2024-05-10 16:27 UTC, namankumar approved these changes

2024-05-10 16:31 UTC, namankumar approved these changes

2024-05-10 16:51 UTC, ElliotFriend approved these changes
awesome! Thank you!

2024-05-10 16:51 UTC, merged