Guide to Deploying a Contract from Installed Wasm Bytecode Using Code
stellar/stellar-docs pull request #737
Opened 2024-06-30 02:20 UTC by KodeSage

Bounty Submission for #614 

Hello @briwylde08

2024-07-01 14:49 UTC, briwylde08 commented
Thank you for your submission! We'll get it reviewed and let you know any feedback. [🎉](https://emojipedia.org/party-popper)

2024-07-01 16:12 UTC, KodeSage commented on docs/smart-contracts/guides/conventions/deploy-contracts-wasm.mdx
> +**NB**: for this example , navigate to `deployer/contracts` and `deployer/deployer` and run the command `stellar contract build` to generate the target files.
alright @briwylde08 , I will change it to `Note` now

2024-07-01 16:20 UTC, KodeSage commented
Hi @briwylde08 , I just updated it now.

2024-07-03 14:33 UTC, KodeSage commented
@briwylde08 was the main branch updated recently? just realised this is showing a merge conflict.

2024-07-03 14:46 UTC, briwylde08 commented
Yeah we did a pretty large structural change yesterday that is probably causing the conflict. You can merge the main branch back into your branch, which should help you resolve whatever conflict is triggering the alert.

2024-07-03 15:42 UTC, KodeSage commented
> Yeah we did a pretty large structural change yesterday that is probably causing the conflict. You can merge the main branch back into your branch, which should help you resolve whatever conflict is triggering the alert.

Hi @briwylde08 @ElliotFriend , I have Updated this branch with current updated folder structure and resolved the conflict.

2024-07-09 16:22 UTC, briwylde08 commented
Hi @KodeSage! Can you comment on the corresponding issue here: https://github.com/stellar/stellar-docs/issues/620 so I can assign it to you? Thank you!

2024-07-09 16:29 UTC, KodeSage commented
Hi @briwylde08 #614 , this is the Bounty issue

2024-07-09 16:37 UTC, briwylde08 commented
Yes sorry I was mistaken!

2024-07-09 18:03 UTC, ElliotFriend reviewed
Looking really good, @KodeSage! I left a couple thoughts, but I think this one is pretty close!

2024-07-09 18:03 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +Invoke the deployed test contract using the identifier returned from the previous command.
```suggestion
Invoke the deployed test contract using the address returned from the previous command.
```

2024-07-09 18:03 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +    value
```suggestion
  -- \
  value
```

2024-07-09 18:03 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +The following output should occur using the code above.
```suggestion
You should receive something like the following output:
```

2024-07-09 22:25 UTC, KodeSage commented
Hi @ElliotFriend , this changes have been implemented, please do take a look on the updated changes and file.

2024-07-10 14:45 UTC, ElliotFriend commented
I'm giving this one another look now, but I can see [it has the extra file](https://github.com/stellar/stellar-docs/compare/main...KodeSage:stellar-docs:deploy_contract_wasm), like in your other PR (#735). Can you get that removed from this PR, too?

2024-07-10 14:51 UTC, KodeSage commented
Hi @ElliotFriend , it's all done now. please take a look at it.

2024-07-10 15:13 UTC, ElliotFriend requested changes
Thanks for making some of the changes, @KodeSage! I've left a few more suggestions on some markdown formatting I missed yesterday. Also, there are still some un-addressed comments/suggested changes from the other review. Not all of them are _must-haves_, of course, but I've noted accordingly any of my comments that are.

Thanks!!

2024-07-10 15:13 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +
```suggestion
```

Let's remove this empty line

2024-07-10 15:13 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +#### How it works
This is one of the changes that I'd like to see happen

2024-07-10 15:13 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +##### **Function breakdown**
This is one of the changes that I'd like to see happen

2024-07-10 15:13 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +##### **Function steps**
This is one of the changes that I'd like to see happen

2024-07-10 15:13 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +- When you deploy a smart contract to a network, you need to specify an identity that will be used to sign the transactions. Change the `0xkodesage` to your own [identity].
This is one of the changes that I'd like to see happen

2024-07-10 15:13 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +- replace `0xkodesage` with your own identity
This is one of the changes that I'd like to see happen

2024-07-10 15:13 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
> +  --source 0xkodesage \
This is one of the changes that I'd like to see happen

2024-07-10 15:16 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contracts-wasm.mdx
This is one of the changes that I'd like to see happen

2024-07-10 15:41 UTC, KodeSage commented
Hi @ElliotFriend , I have implemented the changes. please do take a look at it.

2024-07-10 15:48 UTC, KodeSage commented
Hi @ElliotFriend , I have implemented the updated changes. please do take a look at it.

2024-07-10 16:03 UTC, ElliotFriend requested changes
Hi, @KodeSage! Thanks for making those changes. I have two more nitpicks on the changes for you. It probably seems like I'm just a huge stickler lol. I really appreciate your hard work on this one!

2024-07-10 16:03 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contract.mdx
> +:::note For this example to work, you should navigate to `deployer/contracts` and `deployer/deployer` and run the command `stellar contract build` in each directory to generate the target files. :::
It probably seems like I'm just nitpicking for no reason here 😅, but this change actually does matter. If there's not a blank line after `:::note`, and another before the closing `:::`, the markdown won't be parsed properly.

2024-07-10 16:04 UTC, ElliotFriend commented on docs/build/guides/conventions/deploy-contract.mdx
> +##### **Function steps**
I think this one just got missed the first time-round.

2024-07-10 16:19 UTC, KodeSage commented
HI @ElliotFriend  , I have updated the changes now. 😁

2024-07-10 18:07 UTC, ElliotFriend approved these changes
Looks great! Thanks for all the hard work!

2024-07-10 18:42 UTC, briwylde08 commented
Thank you for your work on this @KodeSage! We'll take the conversation back to the corresponding issue as well.

2024-07-10 18:42 UTC, merged