Deploy a Stellar Asset Contract (SAC) for a Stellar asset using code
stellar/stellar-docs pull request #887
Opened 2024-08-07 12:14 UTC by KodeSage

Bounty PR closes #615

2024-08-08 00:16 UTC, KodeSage commented
@briwylde08 this is ready for review.

2024-08-08 16:13 UTC, briwylde08 commented
Thank you! We'll get this assigned and reviewed!

2024-08-20 23:06 UTC, anataliocs requested changes

2024-08-20 23:06 UTC, anataliocs commented on docs/build/guides/conventions/deploy-sac-with-code.mdx
> +const DeployStellarAssetContract = async () => {
```suggestion
const deployStellarAssetContract = async () => {
```

2024-08-20 23:06 UTC, anataliocs commented on docs/build/guides/conventions/deploy-sac-with-code.mdx
> +DeployStellarAssetContract();
```suggestion
await deployStellarAssetContract();
```

2024-08-20 23:06 UTC, anataliocs commented on docs/build/guides/conventions/deploy-sac-with-code.mdx
> +const DeployStellarAssetContract = async () => {
```suggestion
const deployStellarAssetContract = async () => {
```

2024-08-20 23:06 UTC, anataliocs commented on docs/build/guides/conventions/deploy-sac-with-code.mdx
> +DeployStellarAssetContract();
```suggestion
await deployStellarAssetContract();
```

2024-08-20 23:13 UTC, anataliocs commented
Stellar Asset Contract deployed as expected

![image](https://github.com/user-attachments/assets/ccbb0ca0-68b8-4af9-8de8-3db866406eaf)


https://stellar.expert/explorer/testnet/contract/CBF2X6JDA5BRMITM5VIHACY6YVWX2NRJQ7YN7EN3KXHXWWX66Z3DSMFU
![image](https://github.com/user-attachments/assets/9b4ba1d4-217c-4a3d-b18d-e61f3cd8658a)

2024-08-21 03:16 UTC, KodeSage commented on docs/build/guides/conventions/deploy-sac-with-code.mdx
> +
Hi @anataliocs do you mean `.env` stuff here?

2024-08-21 03:46 UTC, KodeSage commented
Hi @anataliocs , Thank you for the feedbacks.
I pushed up the fixes, which includes
- nesting of sections
- editorial fixes

2024-08-27 14:34 UTC, KodeSage commented
Hello @briwylde08 @anataliocs , just checking in for the status of the review.

2024-08-27 14:39 UTC, briwylde08 commented
Hi @KodeSage! Sorry for the delay! @anataliocs is out of town but will get to the re-review asap!

2024-09-04 09:37 UTC, KodeSage commented
HI @briwylde08 @anataliocs , just checking in again for the status of the review.

2024-09-04 15:04 UTC, briwylde08 commented
Hi @KodeSage!! Sorry for the delay here, will get this reviewed asap. Thank you for the flag!

2024-09-04 16:00 UTC, KodeSage commented
> Hi @KodeSage!! Sorry for the delay here, will get this reviewed asap. Thank you for the flag!

alright thank you @briwylde08

2024-09-04 21:51 UTC, anataliocs approved these changes
Checked out changes locally!  LGTM 🚢 🚢 🚢 

<img width="1492" alt="image" src="https://github.com/user-attachments/assets/eeffd836-758d-4f48-83f4-fd3bfbaa5fe8">

2024-09-05 10:21 UTC, KodeSage commented
> Checked out changes locally! LGTM 🚢 🚢 🚢
> 
> <img alt="image" width="1492" src="https://private-user-images.githubusercontent.com/4750426/364559364-eeffd836-758d-4f48-83f4-fd3bfbaa5fe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzE5NDgsIm5iZiI6MTcyNTUzMTY0OCwicGF0aCI6Ii80NzUwNDI2LzM2NDU1OTM2NC1lZWZmZDgzNi03NThkLTRmNDgtODNmNC1mZDNiZmJhYTVmZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMTAyMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzI0ZjZmODFiN2E5MTAyMTVhZGQzNzIwZDY3NzQzYzNmMzZiM2JjMTliOTIzN2FiNjQ5NzQ0YmU0N2U4MWUzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zQYvsCebBlBnReA9godwYfjJ48aCVn2mSDZ7xbOmBjA">

Thank you @anataliocs 🚀
Hi @briwylde08 this has been approved.

2024-09-05 14:49 UTC, briwylde08 commented
Thanks again for your contribution @KodeSage! We'll take the award conversation back to the corresponding issue.

2024-09-05 14:49 UTC, merged