Extend-wasm-ttl
stellar/stellar-docs pull request #888
Opened 2024-08-07 13:46 UTC by Myestery

fix #618

2024-08-07 13:47 UTC, Myestery commented
@briwylde08 This is ready for review

2024-08-07 16:00 UTC, briwylde08 commented
Thanks for the submission! We'll get it assigned and reviewed. Note that reviews may take longer than normal as we have a lot of submissions to get through!

2024-08-23 12:46 UTC, briwylde08 commented
Hey @Myestery! Sorry for the delay on the review on this. Let me check!

2024-08-27 14:21 UTC, ElliotFriend requested changes
Hi, there @Myestery! This is looking really good! A nice, simple, straight-forward guide. I left a couple minor suggestions for improved markdown file links. I'd also like to see just a bit more information/detail about the `SorobanDataBuilder()` part.

Other than that, this one's nearly ready to go! Thanks for the contribution!

2024-08-27 14:21 UTC, ElliotFriend commented on docs/build/guides/conventions/extending-wasm-ttl.mdx
> +The code below uses Nodejs environment but same concept can also be applied in the browser using Freighter wallet or using any other [Stellar SDK](/docs/tools/sdks/library).
```suggestion
The code below uses Nodejs environment but same concept can also be applied in the browser using the Freighter wallet or using any other [Stellar SDK](../../../tools/sdks/library.mdx).
```

2024-08-27 14:21 UTC, ElliotFriend commented on docs/build/guides/conventions/extending-wasm-ttl.mdx
> +Read more about the Extend Footprint TTL operation [here](https://developers.stellar.org/docs/learn/encyclopedia/storage/state-archival#extendfootprintttlop).
```suggestion
Read more about the Extend Footprint TTL operation [here](../../../learn/encyclopedia/storage/state-archival.mdx#extendfootprintttlop).
```

2024-08-27 14:21 UTC, ElliotFriend commented on docs/build/guides/conventions/extending-wasm-ttl.mdx
> +    .build();
I think it's worthwhile here to describe in a little more detail what the `SorobanDataBuilder()` is doing, and _how_ you're using it. Explain why you're using `setReadOnly()` as opposed to `setReadWrite()`. That kind of stuff.

2024-08-27 19:35 UTC, ElliotFriend approved these changes
This is wonderful! Thanks for the contribution, @Myestery!

2024-08-27 19:41 UTC, briwylde08 commented
Thank you @Myestery! As usual, we'll take the award conversation back to the corresponding issue!

2024-08-27 19:41 UTC, merged