Create 2024-09-12.mdx
stellar/stellar-docs pull request #977
Opened 2024-09-13 07:55 UTC by carstenjacobsen

Adding meeting notes from Stellar Developer Meeting held at 09/12 2024, and adding carstenjacobsen as a contributor.

2024-09-13 20:45 UTC, anataliocs commented
Hey @sreuland you reviewed my meeting notes PR, so I added you to this one, but if someone else should review let me know!

2024-09-13 20:50 UTC, anataliocs requested changes
Reviewed the preview and it looks good:

![image](https://github.com/user-attachments/assets/08fa6996-3795-4d27-b013-021daa7f8046)

@fnando Does this look good to you since you were the presenter? :)

2024-09-13 20:50 UTC, anataliocs commented on meeting-notes/2024-09-12.mdx
> +1. alias
```suggestion
1. Alias
```

2024-09-13 20:50 UTC, anataliocs commented on meeting-notes/2024-09-12.mdx
> +2. snapshot
```suggestion
2. Snapshot 
```

2024-09-16 16:01 UTC, anataliocs approved these changes
LGTM 🚢 

@fnando Any requested changes from your end?  Otherwise, we'll just merge it in.

2024-09-16 17:32 UTC, janewang reviewed
LGTM

2024-09-16 20:05 UTC, merged